sonar.projectKey=AI-BERT-BACKEND_batingeers-stats-service
sonar.organization=ai-bert-backend
sonar.projectName=Batingeers Stats Service
sonar.projectVersion=1.0.0



sonar.sources=src/main/com/aibert/dosw
sonar.tests=tests


sonar.language=py

sonar.exclusions=/pycache/,/*.pyc,/migrations/**


sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8