sonar.projectKey=AI-BERT-BACKEND_batingeers-stats-service
sonar.organization=ai-bert-backend
sonar.projectName=Batingeers Stats Service
sonar.projectVersion=1.0.0

# Código fuente
sonar.sources=src/main/com/aibert/dosw
sonar.tests=tests

# Lenguaje
sonar.language=py
sonar.python.version=3.12

# Exclusiones
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**
sonar.coverage.exclusions=**/tests/**

# Cobertura
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.coveragePlugin=cobertura

# Encoding
sonar.sourceEncoding=UTF-8